typography_spectrum: 0.08430698490701616
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.02495644590817392
  lightness: 0.8378114320803434
  saturation: 0.5241343937814236
  rhythmicContrast: 0.18884244025684893
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.03355783806182444
analytics:
  google: null
  facebook: null
  twitter: null
name: Playbox 2
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Lorem ipsum
description: Test tagline
purpose: []
