name: Keith James
favicon: null
layout_spectrum: 0.6581810663919896
typography_spectrum: 0.9375272539909929
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5811812218744308
  lightness: 0.8748775392305106
  saturation: 0.9338404187001288
  rhythmicContrast: 0.33785356231965125
purpose: []
