name: Keith James
favicon: null
layout_spectrum: 0.49743
typography_spectrum: 0.50428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020808'
    - '#bd0006'
    - '#3f9005'
    - '#99ff08'
    - '#a94c06'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
